/*
 * Copyright (c) 2021 Sebastian Erives
 * Licensed under the MIT License.
 */

package com.github.serivesmejia.eocvsim.workspace.util.template

import com.github.serivesmejia.eocvsim.Build
import com.github.serivesmejia.eocvsim.util.SysUtil
import io.github.deltacv.common.util.loggerForThis
import com.github.serivesmejia.eocvsim.workspace.util.WorkspaceTemplate
import net.lingala.zip4j.ZipFile
import java.io.File
import java.io.IOException

object GradleWorkspaceTemplate : WorkspaceTemplate() {

    private val TAG = "GradleWorkspaceTemplate"

    val logger by loggerForThis()

    val templateZipResource = javaClass.getResourceAsStream("/templates/gradle_workspace.zip")

    override fun extractTo(folder: File): Boolean {
        if(!folder.isDirectory) return false

        val templateZipFile = SysUtil.copyFileIsTemp(
            templateZipResource, "gradle_workspace.zip", true
        ).file

        return try {
            logger.info("Extracting template to ${folder.absolutePath}")

            ZipFile(templateZipFile).extractAll(folder.absolutePath)

            logger.info("Successfully extracted template")
            reformatTemplate(folder) //format necessary template files in the folder
            true
        } catch(ex: IOException) {
            logger.warn("Failed to extract workspace template to ${folder.absolutePath}", ex)
            false
        }
    }

    private fun reformatTemplate(folder: File) {
        val settingsGradleFile = File(folder, File.separator + "settings.gradle")
        val buildGradleFile = File(folder, File.separator + "build.gradle")

        //replace the root project name variable in the file to the root folder name
        SysUtil.replaceStrInFile(settingsGradleFile, "\$workspace_name", folder.name)

        // replace the versions of the eocvsim dependencies in build.gradle to the current ones
        // based on the autogenerated Build.java file
        val fileContents = SysUtil.loadFileStr(buildGradleFile)
            .replace("\$eocvsim_version", Build.standardVersionString)
            .replace("\$opencv_version", Build.opencvVersion)

        SysUtil.saveFileStr(buildGradleFile, fileContents)
    }

}

